### ISSUE TITLE
Channel not fired: onCordovaInfoReady after installing cordova-plugin-device

### ISSUE THREAD

**Issue by diadal** [apache/cordova-plugin-device#118]
# Bug Report
Channel not fired: onCordovaInfoReady after installing cordova-plugin-device

### Environment, Platform, Device

Iphone

### Version information

cordova-plugin-device 2.0.3
quasar framework
Xcode

**Comment by perottosson** [comment]
i got the exact same problem Channel not fired after installing cordova-plugin-device

on android. Did you found a solution?

**Comment by bkamenov** [comment]
I also have the error Channel not fired: onCordovaInfoReady  after installing cordova-plugin-device and deviceready not fired for more than 5 seconds respectively on android@10.1.0

It still works on android@10.0.0

The plugin is crucial and this should work. What could be the reason so we can fork the project and create a pull request?

**Comment by breautek** [comment]
> What could be the reason so we can fork the project and create a pull request?

With the information provided thus far, it's impossible to know the cause. I do know this plugin works in my apps just fine, and we are also running cordova-android@10.1.0 on one of them.

I'd encourage trying to open the Android Studio (Project file located at <cordovaProject/platforms/android> so that you have access to the native logs. This may provide better insights on why the plugin isn't being initialized.

You could also attempt rebuilding the project from scratch by reinstalling all node modules, plugins and the platform, **note** that if you have any custom modifications to your platforms or plugins folder they'll be lost:

```
rm -rf node_modules
rm package-lock.json
rm -rf platforms
rm -rf plugins
npm install
cordova platform add android@10
```

**Comment by bkamenov** [comment]
@breautek, this looks interesting as a proposal. I'll try it. Anyway, I found a temp solution by using android@10.0.0 and <preference name="AndroidInsecureFileModeEnabled" value="true" /> to enable http AJAX requests which I was missing due to blocked:mixed-content (access http from https hosted site - the new way of app page launch).

**Comment by bkamenov** [comment]
The clean install of the project using the bash commands did not resolve the event not firing issue. I confirm everything has been installed fresh. 
Installed stuff:
cordova --version returned 10.0.0, Android SDK API Level 30,  Android SDK Build-Tools 31, Android SDK Command-Line Tools 5.0, Android SDK Platform Tools 31.0.3, OS Environment Windows 10. 

I'll try the Android Studio for more information.

**Comment by bkamenov** [comment]
@breautek, I found the issue!

Some background story:
When having the default config.xml file, the 'deviceready' event fires correctly and loads the app. However, my app does AJAX requests to http, and they get blocked.

For that purpose I added this line in my config.xml:
&lt;preference name="scheme" value="http" /&gt;

Which leads to this debug message:
E/CordovaBridge: gap_init called from restricted origin: http://localhost/index.html

..and later:

I/chromium: [INFO:CONSOLE(1237)] "deviceready has not fired after 5 seconds.", source: http://localhost/cordova.js (1237)
    [INFO:CONSOLE(1230)] "Channel not fired: onCordovaInfoReady", source: http://localhost/cordova.js (1230)
I/chromium: [INFO:CONSOLE(1230)] "Channel not fired: onDeviceNameReady", source: http://localhost/cordova.js (1230)
    [INFO:CONSOLE(1230)] "Channel not fired: onFileSystemPathsReady", source: http://localhost/cordova.js (1230)

And in my config.xml I have:

&lt;access origin="*" /&gt;

...and here is where I get confused:

1. Why only when cordova-plugin-device is installed, it is not fired?
2. What to do to make the origin not restricted?

Any ideas?

**Comment by breautek** [comment]
@NiklasMerz this issue seems to be somewhat related to the web asset loader, or at least the change added in 10.1.0 where we allowed `http` scheme. Not really familiar with this part of the code base, do you have anymore insights?

**Comment by bkamenov** [comment]
I have one idea to do with the origin="*". According to the scheme specs it cannot be just *. I miss the link right now, but in its BNF it was something like origin := <scheme> :// host [:port] where scheme := http | https | file and so on. So may be origin should be origin="http://*" or something like that. On Monday I'll play with it. The stupidity in my case is that our app connects to a local network IP address (192.168.88.123:8090) to a service which is not encrypted and I need the unencrypted option...

**Comment by breautek** [comment]
https://github.com/apache/cordova-android/blob/dc4e065f619ce98d5c38211f5efd759d05959bec/framework/src/org/apache/cordova/CordovaBridge.java#L172-L181

Is the relevant pieces of hte code, it still seems like the default policy if a plugin doesn't handle the access control is to have the origin be `file://` and I think this might be the issue... I think this needs to be dynamic based on the settings (such as finding the configured scheme/hostname)

**Comment by NiklasMerz** [comment]
Looking at the `shouldAllowBridgeAccess` function it just calls the `shouldAllowNavigation` that is handled by the allow list plugin. I don't see the issue looking at this now.

Maybe this is a race condition with [my code](https://github.com/apache/cordova-android/pull/1275/files) that adds defaulst to the allow list?

**Comment by breautek** [comment]
I think it's because `https` is hard-coded here: https://github.com/apache/cordova-android/pull/1275/files#diff-c2eeba9559f1ec42b3e90bd1531f3389a2aab9d199752d4cca70fbf489d92ca0R88

`http` support was added in https://github.com/apache/cordova-android/pull/1298/files -- but it looks like it did cover this actually.

**Comment by NiklasMerz** [comment]
Exactly https://github.com/apache/cordova-android/pull/1298 is the correct change. If you change the hostname to something not `localhost`you get the same issue.

Probably this is really a race condition. Not sure how to solve this right now as allowlist is another plugin that does this.

**Comment by NiklasMerz** [comment]
This should be solved with [this change](https://github.com/apache/cordova-android/pull/1332) in cordova-android
