### ISSUE TITLE
Swift errors on cordova ios export

### ISSUE THREAD

**Issue by Frotty** [apache/cordova-plugin-device#93]
Hi, I wanted to use this plugin in my app but I'm getting errors in xcode:
![Screenshot 2019-03-11 at 16 47 37](https://user-images.githubusercontent.com/1486037/54137181-70e05080-441d-11e9-97a0-6eb4b7cb9ebd.png)
Any idea how to fix this?

I also saw that the npm package is over 1 year old even though there was activity in this repo - why isn't any new version being published?

Cheers

**Comment by janpio** [comment]
> but I'm getting errors in xcode:

I can build a Cordova app with this plugin added both via Cordova CLI and Xcode.

> why isn't any new version being published?

Because the limited number of contributors only have a limited amount of time that was spent elsewhere in the last few months. But you can expect one or more releases of plugins in the next few weeks or months as I am currently working on that.

**Comment by jcesarmobile** [comment]
Not sure what you are doing, but in that screenshot you are not showing this plugin and the errors seems related to Capacitor, so going to close.
