### ISSUE TITLE
Device uuid is null on platform browser

### ISSUE THREAD

**Issue by tauqeer81** [apache/cordova-plugin-device#95]
# Bug Report
Device uuid is null on platform browser
## Problem
By running `ionic cordova run browser` device uuid is null as Device object is empty
### What is expected to happen?
Device info should be there as it supports browser platform

### What does actually happen?
Device object is empty when running the application on browser platform

## Information

Here's my code

`import { Device } from '@ionic-native/device/ngx';`

`constructor(private device: Device) { }`

`console.log('Device UUID is: ' + this.device.uuid);`
Result: `Device UUID is: null`

### Command or Code

`ionic cordova run browser`

### Environment, Platform, Device
Platform is browser using chrome

### Version information

@ionic-native/device": "^5.5.0

Please help me out how to resolve this problem. I have tested the code on android device. It's working fine

**Comment by janpio** [comment]
What value would you expect there?

**Comment by tauqeer81** [comment]
> What value would you expect there?

I expect `device` object should have some values like `device.platform`, `device.model` etc.

**Comment by janpio** [comment]
Does the plugin return nothing at all or just not the uuid?
And again, what should the uuid field be filled with? What value should be in there and where should it come from? What is the `uuid` of a browser?

**Comment by cyptus** [comment]
as iOS does not share the UUID which is generated by the plugin from instance to instance (lost after reinstall) i do fallback on a generated GUID which is then saved to localstorage.

**Comment by erisu** [comment]
The browser platform does not have access to the devices UUID. This is why `null` is returned for the browser platform.

There are alternatives that you can implement on your own for example `Fingerprint.js`. The goal of `Fingerprint.js` is to use all of the features that the browser has access to create a unique identifier. They advertise a 99.5%  identification accuracy. There is a drawback where a user can do something to make the identifier change.

@janpio for some additional feedback to your question, if the browser had the access permission, the UUID would be most likely related with the OS or a hardware ID.

For example:

-  **macOS** would fetch the UUID from `IOPlatformUUID`. If you have a Mac, you can test this with `ioreg -rd1 -c IOPlatformExpertDevice | grep IOPlatformUUID`
- **Windows** would use the `MachineGuid` from the registry but _can be edited with administrator permission_.
- **Linux** would use the `dbus` `machine-id`, but _can be changed with root access_.

For Electron, I have been looking at some npm modules that would use the information that I posted in the example above. Unfortunately, browser, just does not have the necessary permission to access this level of information of the OS for security reasons. Because of that, users must find alternatives solutions like `Fingerprint.js` or create their own UUID and store it somewhere like IndexDB.
